### ISSUE TITLE
Code Orgnaization With huge schema

### ISSUE THREAD

**Issue by husseinraoouf** [davidpdrsn/juniper-from-schema#58] opened 2019-08-21 15:47 UTC
I have been trying to use juniper-from-schema for a personal project but i couldn't know how to structure project properly to handle many query and mutation fields

currently when parsing a schema that have many Query fields maybe over 20 field i have to implement all 20 fields in a single `impl` block which isn't perfect, i would like to better split implementation on different files

i think there is better way to do this and maybe but an example of it as it is not really obvious how to do it

and thank you for the great library

**Comment by davidpdrsn** [comment] 2019-08-21 16:45
There has been similar requests to juniper itself. See https://github.com/graphql-rust/juniper/issues/182 and https://github.com/graphql-rust/juniper/issues/394.

When I run into a type with lots of (or a few complicated) fields I normally extract the resolver code into functions. For example:

```rust
fn field_primary_team(
    &self,
    exec: &Executor<'_, Context>,
    trail: &QueryTrail<'_, Team, Walked>,
) -> Result<Option<&Team>, ReportableError> {
    resolve_user_primary_team()
}
```

While this doesn't solve the root problem of wanting to break things into separate impl blocks, it does enable a bit more structure.

I haven't been able to think of a better solution at doesn't require official support from juniper.

**Comment by davidpdrsn** [comment] 2019-09-13 11:45
I consider this a duplicate of https://github.com/davidpdrsn/juniper-from-schema/issues/60. So lets keep the discussion there.

**Closed by davidpdrsn** 2019-09-13 11:45 UTC
